##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shiro-example?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: yuqingbo
    druid:
      initial-size: 5

  redis:
    host: 118.24.224.186
    port: 6379
    password: cqpolice

logging:
  level:
    root: info
    druid.sql.Statement: debug
    com.cnaidun: debug


projectPath: D:\\gab_tmp