##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://118.24.232.195:3306/gab_sx_service?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: wangzhiyong
    password: WangZhiYong*0529!
    druid:
      initial-size: 5

  redis:
    host: 118.24.224.186
    port: 6379
    password: cqpolice

logging:
  level:
    root: info
    druid.sql.Statement: debug
    com.cnaidun: debug


projectPath: C:\\gab_tmp